server:
  port: 9000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: order-service
        uri: lb://ORDER-SERVICE/order
        predicates:
        - path=/order/**
#        filters:
#        - RewritePath=/order/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
logging:
  level:
    org.springframework.cloud.gateway: debug