server:
  port: ${PORT:9000}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: inventory-service
        uri: lb://inventory-service/order
        predicates:
        - Path=/inventory/**
      - id: order-service
        uri: lb://order-service/order
        predicates:
        - Path=/order/**
        # filters:
        # - RewritePath=/order/(?<path>.*), /$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registerWithEureka: false

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: INFO
    reactor.netty: INFO