server:
  port: 8761
spring:
  application:
    name: service-discovery
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    com.netflix.eureka: true
    com.netflix.discovery: true