server:
  port: 8082
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  data.mongodb:
    host: mongodb
    port: 27017
    database: bookstore

service:
  inventory: http://localhost:8081/inventory

api:
  inventory:
    getItemById: ${service.inventory}/items/%s