server:
  port: 8082
  servlet:
    context-path: /order

spring:
  application:
    name: order-service
  data.mongodb:
    host: localhost
    port: 27017
    database: bookstore

service:
  inventory: inventory-service

api:
  inventory:
    item: inventory/items